### ISSUE TITLE
Why a custom backend?

### ISSUE THREAD

**Issue by belcarozo** [flexible-agency/react-native-check-version#29]
I'm just trying to better understand what is the advantage of having a web service 
to help the react-native-check-version package. Thanks in advance 😄

**Comment by tschoffelen** [comment]
Hey! That's a good question, that I've been pondering over quite a bit over the last couple of weeks actually.

The initial idea was:

1. It would be easier to quickly fix any breaking changes in our way of scraping version numbers if Google (or Apple, but they have a proper API) were to change their Play Store web pages.
2. It allows us to do some server-side caching to speed up those requests a bit.

However, the package has been becoming more popular over the last couple of months, with now more than 25M+ requests per month, which is starting to get expensive on my end 😄 

So I'm thinking of starting work on a new version that indeed does the calls to Google and Apple directly from the app, rather than via a separate web service.

**Comment by tschoffelen** [comment]
Closing to continue convo in #30.
