### ISSUE TITLE
Be more flexible on version number parsing

### ISSUE THREAD

**Issue by marcelxsilva** [flexible-agency/react-native-check-version#7]
The application in the store is in version 0.6

Inside package.json version 0.8 is set

It turns out that the version of the app being greater than the version that is in the store it informs that it needs updating.

> update added image

<img width="959" alt="Captura de Tela 2021-01-21 às 18 03 42" src="https://user-images.githubusercontent.com/44801113/105412112-08667b00-5c13-11eb-96a0-38a709be8265.png">

**Comment by tschoffelen** [comment]
Hi! Thanks for using the library.

We don't use the version inside of package.json, but instead look at the version of the native app. Can you confirm the native app version is really newer than the app store version?

**Comment by marcelxsilva** [comment]
@tschoffelen Thanks for your response.

Yes, the app version is bigger than the store version

**Comment by tschoffelen** [comment]
Ah, thanks for the screenshot, that helps. The library is optimized for version numbers that follow the [`semantic versioning` (semver) scheme](https://semver.org/).

`0.8` is technically not a valid semantic version (`0.8.0` would be), which is why it gives that error in the `notice` field.

However, I personally would expect it to be able to deal with this type of version numbers, so I will see what can be done to make the back-end work with `<major>.<minor>` version numbers.

**Comment by tschoffelen** [comment]
I've released an update that now should report the correct value for the `needsUpdate` field. Note that it can take up to an hour for this change to start showing up due to caching.

And of course let me know if this still is a problem.
